### ISSUE TITLE
Retrieving status for an order

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#110]
How do we retrieve status for a created order with this library?

Setting the return URL is not enough security and cannot assure that an order has been approved.
->setIdentificationConfirmationUrl('https://mydomain.com/successful-authentication')

Letting the end-user carry critical information is not reliable. The industry standard approach is to retrieve current status from the payment service provider. But the documentation has no mentioning how to retrieving status.
![image](https://github.com/sveawebpay/php-integration/assets/359192/033c53e8-55c7-4570-825e-08352b8969d3)

**Comment by Marwzoor** [comment]
You can get the order with the WebPayAdmin-interface described in the documentation:
https://github.com/sveawebpay/php-integration#73-webpayadminqueryorder-
