### ISSUE TITLE
Feature suggestion: Availability check

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#13]
For stores with international sales, it would be very convenient if a simple check with the framework could be done, asking if the session customer can use sveawebpay for checkout BEFORE even rendering the checkout option.

Proposal example:

$result = WebPay::checkAvailability()
  ->setPaymentMethods(...)
  ->setCurrency("GBP")
  ->setCountry("GB")
  ->setLanguage("en")
      ->doCheck()

// should we continue displaying the checkout option?
// ...
## 

Otherwise one would always have to manually check if i.e. the currency is within the allowed list of currencies. When sveawebpay expands and adds support for new countries, these statements would manually need to be edited in each and every customer installation.

**Comment by fre-sund** [comment]
Closing this since we have a method to check if the currency is allowed in 3.6.0
