### ISSUE TITLE
individualCustomer() and companyCustomer() merged

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#15]
I assume the need to solve the logic is what makes us have to separate the behaviors for creating an order using the SWP framework.

However I find the two methods individualCustomer() and companyCustomer() possible to merge.

A universal method could something like this:

Proposal:

->addCustomerDetails(
    Item::Customer()
    ->setTaxId("000000-0000")
    ->setCompanyName("ACME Inc.") // Required if TaxId validates as comany
    ->setName("John", "Doe")
    ->setCoAddress("c/o Simpsons")
    ->setStreetAddress("Street", 7)
    ->setZipCode(9999)
    ->setLocality("Timbuktu")
    ->setEmail("john@acme.com")   
    ->setIpAddress("0.0.0.0")
    ->setPhoneNumber(081234567)
    )

Hypothetical changes from merging individualCustomer() and companyCustomer():
- - setCompanyIdNumber - Replaced by TaxId
- - setVatNumber - Replaced by TaxId
- - setSsn - Replaced by setTaxId
- + setTaxId
- - setInitials - Removed, instead extract the first character of the first and last word/name in "Vincent van Gogh"
- - setBirthDate - Can be extracted from TaxId if validated as an individual
- * SetCompanyName - If set, triggers isCompany
- * setStreetAddress - Accepts both ("Gatan 23") or ("Gatan", 23)

Benefits for the store / user-end:
* Removes the logic needed to separate a company from an individual.
* Removes the logic needed to separate 23 from "Gatan 23".
* Removes the logic needed to extract or keep track of birthdays.
* Removes the logic needed to separate SE19000000000001 from 000000-0000.
* Removes the need to keep track or solve the logic for initials.

How to tell if a swedish tax Id is a company or individual.
http://sv.wikipedia.org/wiki/Organisationsnummer

VATIN formats
http://en.wikipedia.org/wiki/VAT_identification_number

If birthdays cannot be extracted from NL or DE individuals Id-numbers I suppose the setBirthDate must stick.

Thoughts?

**Comment by kilskrift** [comment]
Just a heads-up to say that for some time now, the IndividualCustomer and CompanyCustomer classes setStreetAddress($street, $housenumber) method has accepted one or two arguments . 

If no housenumber is given, the entire street address including any housenumber can be found in street attribute, with housenumber set to null.

The recommended way is to use a single argument, unless your customer is based in NL or DE.

/kgm
