### ISSUE TITLE
How to setInvoiceDistributionType without delivering order

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#38]
My client wants to preset setInvoiceDistributionType for the order without delivering the invoice. The reason is because my client collects the choice of e-invoice or paper invoice in the session during checkout.

From my understanding this is not possible in WebPay::createOrder(), so how do we do it? And shouldn't this setting be a part of useInvoicePayment()?

**Comment by kilskrift** [comment]
Filing this thread per OP suggestion. Thanks for the input.
