### ISSUE TITLE
[Feature Suggestion] Missing defined currency in getPaymentPlanParams()

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#41]
I just found out the currency for the result parameters fromAmount and toAmount from getPaymentPlanParams() is fixated by the clientNo. This requires internal logic keeping track of which clientNo the integration package made use from during the call.

An additional parameter currencyCode in the result both answers our questions and does most of the work for us.

**Comment by kilskrift** [comment]
Closing this issue.
