### ISSUE TITLE
[Feature Request] Card matters

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#44]
I am sending a bit of criticism when it comes to (un)conventional payment flows and operations.

Problem 1:
While initiating a card transaction we are asked for the orderId in setClientOrderNumber(). If the user presses the Cancel button or go "javascript:history.go(-1)" the orderId is blocked for any transaction completion and completely locked out from reselecting card payment. Now SWP did activate a tweak to recover from a clicked Cancel button. But it doesn't solve the browser back button which is a conventional method in any browser to go back to a previous page.

If we append a timestamp to the orderId we lack the ability to match our database with your database.

Problem 2:
Unconvetionally while canceling a card payment, instead of being redirected back to checkout. It seems setCancelUrl() is ignored. Instead the user is redirected to order processing which fails with the error Cannot be verified - Canceled.

**Comment by kilskrift** [comment]
Closing this, thanks for the input.
