### ISSUE TITLE
createOrder doesn't add non-cost products

### ISSUE THREAD

**Issue by TXC** [sveawebpay/php-integration#51]
If i use the _WebPay::createOrder()->addOrderRow()_ method and add Shipping/Invoice-products they don't get added.
But if i use _WebPayAdmin::addOrderRows(...)->addOrderRows()_ it will be added

**Comment by kilskrift** [comment]
Current package behaviour has been documented in the section 5 of the Documentation. 

Also, a general review of the order rows are or are not grouped by the package has been added to the development backlog.

/kgm
