### ISSUE TITLE
SoapFault in GetOrders

### ISSUE THREAD

**Issue by keviny86** [sveawebpay/php-integration#54]
I get this error message when trying to query an order:

SoapFault: Server did not recognize the value of HTTP Header SOAPAction: http://tempuri.org/IAdminService/GetOrders. in SoapClient->__soapCall() (line 61 of /src/AdminService/admin_soap/SoapClient.php).

**Comment by keviny86** [comment]
Same error for http://tempuri.org/IAdminService/GetOrders

**Comment by kilskrift** [comment]
Hi again,
unfortunately I'm unable to replicate this. 

Does the error occur when you run the tests in i.e. GetOrdersRequestIntegrationTest.php? 

Are you able to provide us the actural request xml? 

Feel free to use email webpay-modules@sveaekonomi.se if you prefer to keep them private.

/kgm

**Comment by kilskrift** [comment]
Unable to replicate, closing the issue.
