### ISSUE TITLE
Card payment by Country

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#58]
getTestConfig() or getProdConfig() does not resolve what pay page credentials should be used if the customer is identified by e.g. country US.

I am informed this is registered as an issue in you backlog. But I would like to open a github ticket so there is something I can follow.

PS: Clients complain SveaConfig.php is messy and difficult to ride if you are not a developer. It's neither obvious to them to scroll down a page to edit additional credentials for production.

**Comment by timint** [comment]
Any updates?

**Comment by nlii** [comment]
Yes, this is still an issue, but has not yet been prioritised to a sprint backlog.
This is a problem if you use the file SveaConfig directly. We do recomend you implement the ConfiruationProvider interface and let the functions return the authorization values instead.

https://github.com/sveawebpay/php-integration/blob/master/src/Config/ConfigurationProvider.php

 In that way you do not have to be depending on countrycode on cardorders. Just let these the functions  return the authorization values. Weater it is from a configuration interface or just hardcoded in the functions.

```
 /**
     * fetch merchant id, used with card or direct bank payments (i.e. Svea Hosted Web Service API)
     *
     * @return string
     * @param string $type  ConfigurationProvider::INVOICE_TYPE, ::PAYMENTPLAN_TYPE can be used if needed to match different configuration settings
     * $param string $country CountryCode eg. SE, NO, DK, FI, NL, DE
     */
    public function getMerchantId($type, $country);
    /**
     * fetch secret word, used with card or direct bank payments (i.e. Svea Hosted Web Service API)
     *
     * @return string
     * @param string $type  ConfigurationProvider::INVOICE_TYPE, ::PAYMENTPLAN_TYPE can be used if needed to match different configuration settings
     * $param string $country CountryCode eg. SE, NO, DK, FI, NL, DE
     */
    public function getSecret($type, $country);

```

Integration example in our Opencart module:
https://github.com/sveawebpay/opencart-module/blob/master/src/svea/Config/OpencartSveaConfigTest.php

**Comment by timint** [comment]
Soon there is an anniversary celebartion of this issue. I'm bumping this thread as a couple of clients are STILL waiting for an official solution to the problem.

The following attempted tweaks failed.

```
    /**
     * @param string $type one of { \ConfigurationProvider::HOSTED_TYPE, ::INVOICE_TYPE, ::PAYMENTPLAN_TYPE }
     * @param string $country
     * @return string
     * @throws Exception
     */
    public function getMerchantId($type, $country) {
        //return $this->getCredentialsProperty('merchantId', $type, $country);
        return '0000';
    }

    /**
     * @param string $type one of { \ConfigurationProvider::HOSTED_TYPE, ::INVOICE_TYPE, ::PAYMENTPLAN_TYPE }
     * @param string $country
     * @return string
     * @throws Exception
     */
    public function getSecret($type, $country) {
        //return $this->getCredentialsProperty('secret', $type, $country);
        return 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
    }
```
**Invalid or missing Country code**


```
    /**
     * @param string $type one of { \ConfigurationProvider::HOSTED_TYPE, ::INVOICE_TYPE, ::PAYMENTPLAN_TYPE }
     * @param string $country
     * @return string
     * @throws Exception
     */
    public function getMerchantId($type, $country) {
        //return $this->getCredentialsProperty('merchantId', $type, $country);
        return $this->getCredentialsProperty('merchantId', $type, 'SE');
    }

    /**
     * @param string $type one of { \ConfigurationProvider::HOSTED_TYPE, ::INVOICE_TYPE, ::PAYMENTPLAN_TYPE }
     * @param string $country
     * @return string
     * @throws Exception
     */
    public function getSecret($type, $country) {
        //return $this->getCredentialsProperty('secret', $type, $country);
        return $this->getCredentialsProperty('secret', $type, 'SE');
    }
```
**Invalid or missing Country code**

**Comment by jkuikka** [comment]
I don't understand why it isn't possible to use the card service in all different countries?

**Comment by nlii** [comment]
A fix is made in commit 7555da0efa111dbc41f4bb5ecfe41183ab9a3723. 

This fix is if you implement the authorization values by putting hardcoded values in the file SveaConfig.php but not want to be limited to use card payment by Contry. Alternative implement the interface ConfigurationProvider.php where cardpayments is not limited by country. 


Put your authorization values in the files:

config_test.php and get an config object with:
SveaConfig::getTestConfig() and in 

config_prod.php if you get the config object with:
SveaConfig::getProdConfig()

Remember to keep thoose files seperate when updating the library!

This fix has change the file SveaConfig.php and added the files config_test.php and config_prod.php in the Config catalog.

This fix will be released in the next library updat, but is free to be used as a Beta version from develop branch. Bevare that version includes some big changes like Namespace refactoring for Composer compatibility.

**Comment by timint** [comment]
The dev branch has issues with the autoloader. I am unable to even initiate the object as it cannot find or load the class files.

```
      require_once(FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'sveawebpay/2.3.0/Includes.php');

      if ($this->settings['gateway'] == 'Live') {
        $config = Svea\SveaConfig::getProdConfig();
      } else {
        $config = Svea\SveaConfig::getTestConfig();
      }

      $swp = WebPay::createOrder($config);
```

Is it possible you can wrap up a solution fit for the current master or take 2.3.0 to production any time near? The latest module out is using 2.2.22.

**Comment by nlii** [comment]
Sorry, the description of how to use the new files in comment above was not correct, and I now updated that comment. 

To get your example working:
-	Location of Includes.php file is located in src directory, so when this library is placed in some project, it should be called regarding that new file location.
-	Location of Includes.php file should not be changed and moved from this src directory
-	Whole library is now placed under new Namespace “Svea\WebPay”
-	Namespaces are now changed and SveaConfig file is changed as well, so correct way of calling this getProdConfig() function is with full namespace path “Svea\WebPay\Config\ConfigurationService::getProdConfig”,
-	Class WebPay is also under namespace, so the new call In this example will be Svea\WebPay\WebPay::createOrder($config).


Corrected example:
```
    require_once(FS_DIR_HTTP_ROOT . WS_DIR_EXT . 'sveawebpay/2.3.0/<src_directory>/Includes.php'); // this should point to new path of Includes.php file

      if ($this->settings['gateway'] == 'Live') {
        $config = Svea\WebPay\Config\ConfigurationService::getProdConfig();
      } else {
        $config = Svea\WebPay\Config\ConfigurationService::getTestConfig();
      }                                   

      $swp = Svea\WebPay\WebPay::createOrder($config);
```

**Comment by timint** [comment]
That works better!

When it comes to the autoloader of this new namespace. Here are some improvements:

```
function __autoload_svea_php_integration_library_classes($className)
{
    if (!preg_match('#^(Svea\\\\WebPay)#', $className)) return;

    $fullPath = preg_replace('#^(Svea\\\\WebPay)#', __DIR__, $className) . '.php';
    $fullPath = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $fullPath);

    if (file_exists($fullPath)) include $fullPath;
}
spl_autoload_register('__autoload_svea_php_integration_library_classes', false, true);
```

* preg_match don't respond to other frameworks/namespaces.
* preg_replace fullpath
* Directory separator washing. Not sure if include() is concerned, but the windows directory separator \ has during the years been problematic on non-win machines.
* The use of is_file rather than file_exists makes sure the file is not a directory (file_exists matches both).
* include rather than include_once as include_once is a performance drainer and is not needed as the autoloader only kicks in if the file is not included.
* The flag true for prepending the autoload rule rather than appending. Fixes issues with projects that do not honour the PSR autoloading standards.

**Comment by timint** [comment]
Still having problems. I think it derives from the following line when we send in the customer details:
`      $swp->setCountryCode($order->data['customer']['country_code']);`

A customer from Great Britain is denied card payment. I need to do some debugging and might update this post later.

**Comment by timint** [comment]
> Hej,
> Felmeddelandet ” Invalid or missing Country code”
> Kastas när man använder SveaConfigurationProvider med fel countrycode.
> 
> Kan du kontrollera så du använder ett configobject från ConfigurationService istället.
> 
> Ex:
> $config = Svea\WebPay\Config\ConfigurationService::getTestConfig();
> 

Here is the code for the config. This has been a problem in 2.2.22 as well although using a tweak for the config problem. I don't think it's related to config. As it seems to be `$swp->setCountryCode('GB');` that causes the problem.

      if ($this->settings['gateway'] == 'Live') {
        $config = Svea\WebPay\Config\ConfigurationService::getProdConfig();
      } else {
        $config = Svea\WebPay\Config\ConfigurationService::getTestConfig();
      }

      $swp = Svea\WebPay\WebPay::createOrder($config);

**Comment by fre-sund** [comment]
Since 3.0.0 solves this issue, I'll close this.
