### ISSUE TITLE
Undefined class constant 'SVEACARDPAY'

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#64]
Is SVEACARDPAY not supported in version 2.2.22 ?

`$swp->usePaymentMethod(PaymentMethod::SVEACARDPAY)`

**Fatal error:** Uncaught Error: Undefined class constant 'SVEACARDPAY'

**Comment by nlii** [comment]
The paymentmethod SVEACARDPAY was added in commit e9d472d8a69d279601f5b6a21f3aa26129a5b37e and in release 2.3.0
