### ISSUE TITLE
CardPay: Transaction rejected by bank.

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#65]
The following code gives me an immediate error saying "Transaction rejected by bank." The expected result was a payment window URL. Using the public test account 1130.

```
        $response = $swp->usePaymentMethod(Svea\WebPay\Constant\PaymentMethod::SVEACARDPAY)
                        ->setCardPageLanguage($order->data['language_code'])
                        ->setReturnUrl(document::ilink('order_process'))
                        ->setCancelUrl(document::ilink('checkout'))
                        ->getPaymentUrl();

        if (empty($response)) throw new Exception('No response from Svea Ekonomi');

        if (!empty($response->errormessage)) throw new Exception($response->errormessage);
```

What to do?

**Comment by nlii** [comment]
If you send an email to support-webpay@sveaekonomi.se with a date and a clientOrderNumber, our helpdesk can search in the logs to se what went wrong with this request.

**Comment by fre-sund** [comment]
Are you using the specific card details for SVEACARDPAY? They are different from the ones that are provided for KORTCERT.

**Comment by timint** [comment]
Fredrik, I'm just trying to retrieve the paymentURL. I don't even get to the point where I can insert card details. I'll try giving you a quick call before registering a support ticket.

**Comment by timint** [comment]
Error was related to currency USD. Thanks F&A. 

Thread closed as new ticket for improvemnets opened at https://github.com/sveawebpay/php-integration/issues/67.
