### ISSUE TITLE
Documentation 2.3.0+

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#66]
The documentation is vastly outdated when it comes to the framework rebuild of version 2.3.0.

Found some typos

`$request = WebPayAdmin.updateOrder($config)`

`->setCardPageLanguage("se")`

The Appendix is a bit scrambled.

If you are into perfection there is some inconsistent use of 'single' and "double" quotes. :)

**Comment by fre-sund** [comment]
This is now fixed, let me know if you stumble upon something else :)

**Comment by timint** [comment]
I see you guys have been busy! :) Looking good!
