### ISSUE TITLE
[Feature Request] Supported CardPay currencies

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#67]
If an unsupported currency is set the error is confusingly general saying "Rejected by bank".

Suggestion for improvements:
1. Return a specific error message: USD is not a supported currency for this method.
2. Ability to return available currencies e.g. getCardPayCurrencies(). That way we can just validate against a returned list of currencies. And new currencies would automatically be enabled dynamically by modules.

**Comment by fre-sund** [comment]
Added in 3.6.0
