### ISSUE TITLE
Cannot install composer package

### ISSUE THREAD

**Issue by jannejava** [sveawebpay/php-integration#69]
Cannot install as a composer package as stated in the documentation:

`composer require svea/webpay`

Gets the response:

` [InvalidArgumentException]
  Could not find package svea/webpay at any version for your minimum-stability (stable). Check t
  he package spelling or your minimum-stability`

**Comment by jannejava** [comment]
Update the documentation to

`composer require sveaekonomi/webpay`

**Comment by jstev** [comment]
Thank you for suggestion, the issue has been fixed.
