### ISSUE TITLE
Error upgrading from 3.0.0 to 3.1.1

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#72]
Warning: require_once(Svea\Checkout\Transport\Connector.inc.php): failed to open stream: No such file or directory

Triggered via ConfigurationService.php

```
namespace Svea\WebPay\Config;

use Svea\Checkout\Transport\Connector;
```

Any clues?

**Comment by timint** [comment]
Anyone?

**Comment by nlii** [comment]
Could you please specify more information about how to reproduce this issue, like php version, platform, operating system, composer etc. The file Connector.inc.php does not exist in our php-checkout library. Do you use a custom configuration? Please email support-webpay@sveaekonomi.se with more details.

**Comment by timint** [comment]
I was using the 3.0.0 master release configured using Config/config_prod.php.

My autoloader looks like this:

```
function __autoload_svea_php_integration_library_classes($className)
{
    if (!preg_match('#^(Svea\\\\WebPay)#', $className)) return;

    $fullPath = preg_replace('#^(Svea\\\\WebPay)#', __DIR__, $className) . '.php';
    $fullPath = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $fullPath);

    require $fullPath;
}
spl_autoload_register('__autoload_svea_php_integration_library_classes', false, true);

```

The only file modified is config_prod.php.

**Comment by timint** [comment]
**Ping**

**Comment by sveateam** [comment]
Hi,
the problem could be, looking into this autoload part of code, that checkout package is not loaded anywhere. This library use Checkout library, so you will need that library and autoload for that as well.
Usually composer looks after this things and all package dependencies.
Hopefully this will fix your problem.

**Comment by timint** [comment]
I am not using Svea Checkout. No plans of using it neither.

If Svea Checkout is dependancy for the old regular payment methods card, invoice, etc. It might be a brilliant idea to merge this repository with Checkout.

**Comment by TXC** [comment]
@timint this repository is using "Svea Checkout" as a dependency in composer.json, so if you are using composer is should solve itself.

**Comment by fre-sund** [comment]
No changes to how dependencies of the integration packages work is planned as of now. Closing this for now.
