### ISSUE TITLE
Wrong and conflicting classname in file

### ISSUE THREAD

**Issue by sirn-se** [sveawebpay/php-integration#81]
The file `src/AdminService/AdminSoap/CreditInvoiceRequest.php` defines the class `CreditInvoiceRowsRequest`, which should (obviously) be `CreditInvoiceRequest` instead.

The class `CreditInvoiceRowsRequest` is already (correctly) defined in file`src/AdminService/AdminSoap/CreditInvoiceRowsRequest.php`, also causing to a conflict in class loading.

**Comment by sirn-se** [comment]
Or possibly, the file `src/AdminService/AdminSoap/CreditInvoiceRequest.php` should simply be removed. I can´t see the class `CreditInvoiceRequest` being used.

**Comment by fre-sund** [comment]
I'll take a look at it this afternoon. Thanks for reporting the issue!

**Comment by fre-sund** [comment]
You're right, it's not being used and it seems like its just a copy of CreditInvoiceRowsRequest except for the filename. I've removed the file and published a new release.

Closing this issue, thanks again!
