### ISSUE TITLE
Wrong return type in docblock for doRequest() in WebServicePayment class

### ISSUE THREAD

**Issue by themichaelhall** [sveawebpay/php-integration#84]
The DocBlock for method `doRequest()` in `WebServicePayment` class says that an instance of `CreateOrderEuResponse` should be returned. Instead a `CreateOrderResponse` is returned (at least in my case, I have not tested all different responses that can be returned from that method).

https://github.com/sveawebpay/php-integration/blob/master/src/WebService/Payment/WebServicePayment.php#L45

Although not an critical issue, it makes PhpStorm display an annoying warning when passing the result in another method that takes this instance via a typed parameter.

`Expected parameter of type '\Svea\WebPay\WebService\WebServiceResponse\CreateOrderResponse', '\Svea\WebPay\WebService\Payment\CreateOrderEuResponse' provided`.

The actual code works fine though :-)

Best regards

/Michael

**Comment by fre-sund** [comment]
Hi Michael,

Thank you for reporting this issue, I've commited a fix(c022cb439c0ac289c9d7a9cd757e6323dc7648e9) for this in the develop branch which will be merged into the master branch in the future.

Best regards,
Fredrik
