### ISSUE TITLE
Fatal error: Uncaught Error: Undefined class constant 'DBNORDEAFI'

### ISSUE THREAD

**Issue by timint** [sveawebpay/php-integration#89]
I am unable to perform a specific test with Nordea Finland. I am told to use DBNORDEAFI.

`          $response = $swp->usePaymentMethod(\Svea\WebPay\Constant\PaymentMethod::DBNORDEAFI)`

Fatal error: Uncaught Error: Undefined class constant 'DBNORDEAFI' 

For the full set of code:

```
      try {

        require_once FS_DIR_APP . 'ext/sveawebpay/autoloader.php';

        $config = Svea\WebPay\Config\ConfigurationService::getTestConfig();

        $swp = Svea\WebPay\WebPay::createOrder($config);

        $swp->addCustomerDetails(....);

        $swp->addOrderRow($orderRows);

          $response = $swp->usePaymentMethod(\Svea\WebPay\Constant\PaymentMethod::DBNORDEAFI)
                    ->setPayPageLanguage($order->data['language_code'])
                    ->setReturnUrl(document::ilink('order_process'))
                    ->setCancelUrl(document::ilink('checkout'))
                    ->getPaymentUrl();

      } catch ( \Exception $e ) {
        die($e->getMessage());
      }
```

Using the following test account:

```
    'commonCredentials' => array(
        'merchantId' => '6708',
        'secret' => 'a1.........................................................31'
    ),
```

**Comment by alexanderwiden95** [comment]
Hi,

If you'd like to use "DBNORDEAFI" you either enter it directly or use the constant \Svea\WebPay\Constant\PaymentMethod::**NORDEA_FI**

```php
$order->usePaymentMethod(\Svea\WebPay\Constant\PaymentMethod::NORDEA_FI);
```

or

```php
$order->usePaymentMethod('DBNORDEAFI');
```

The constants can be seen here:
https://github.com/sveawebpay/php-integration/blob/master/src/Constant/PaymentMethod.php#L20

**Comment by timint** [comment]
Thank you. Confirmed that the following works:

$order->usePaymentMethod(\Svea\WebPay\Constant\PaymentMethod::NORDEA_FI);

You should put ALL the definitions in the documentation.
